[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_friend = "CeQk2BBaT2rua9mmMKWkwyCY6JcdLQND2wdYGeVEp9TT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "validator.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
